Update GeneralGraph.py
py-why/causal-learn pull request #118
Opened 2023-06-23 21:31 UTC by JanMarcoRuizdeVargas

Pull request to fix GeneralGraph.subgraph() axis out of bounds error. Referring to https://github.com/py-why/causal-learn/issues/117

2023-06-28 12:15 UTC, kunwuz requested changes
Hi, thanks for the fix! I think the modification is correct. @chenweiDelight please let me know if you would like to double-check this :)

2023-06-28 12:15 UTC, kunwuz commented on causallearn/graph/GeneralGraph.py
> +                nodes_to_delete .append(i)
Minor: perhaps we could move the space here? 'nodes_to_delete.append(i)' -> nodes_to_delete .append(i)

2023-06-28 23:03 UTC, JanMarcoRuizdeVargas commented
Hi, yes of course, I deleted the space.

2023-07-06 19:22 UTC, kunwuz approved these changes

2023-07-06 19:22 UTC, merged